package com.attendance.attendanceapp.ui.screens.onboarding

import androidx.compose.animation.core.animateDpAsState
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.School
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.graphics.asImageBitmap
import android.graphics.BitmapFactory
import androidx.compose.runtime.remember
import kotlinx.coroutines.launch

data class OnboardingPage(
    val title: String,
    val description: String,
    val imageAsset: String, // Asset filename
    val backgroundColor: Color
)

@Composable
fun OnboardingScreen(
    onFinished: () -> Unit
) {
    val pages = listOf(
        OnboardingPage(
            title = "Digital Attendance",
            description = "Say goodbye to paper sheets. Track attendance effortlessly with our smart digital solution.",
            imageAsset = "attendance.webp",
            backgroundColor = Color(0xFF006064)
        ),
        OnboardingPage(
            title = "Quick QR Scan",
            description = "Students can mark their presence in seconds by simply scanning a secure QR code generated by the teacher.",
            imageAsset = "scanner.jpeg",
            backgroundColor = Color(0xFF006064)
        ),
        OnboardingPage(
            title = "Real-time Reports",
            description = "Get instant insights and automated reports for every class session. Export data with one tap.",
            imageAsset = "report.webp",
            backgroundColor = Color(0xFF006064)
        )
    )

    val pagerState = rememberPagerState(pageCount = { pages.size })
    val scope = rememberCoroutineScope()

    Box(modifier = Modifier.fillMaxSize().background(Color.Black)) {
        // Upper background color area (dynamic based on page)
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .fillMaxHeight(0.5f)
                .background(pages[pagerState.currentPage].backgroundColor)
        )

        Column(modifier = Modifier.fillMaxSize()) {
            HorizontalPager(
                state = pagerState,
                modifier = Modifier.weight(1f)
            ) { position ->
                OnboardingPagerContent(pages[position])
            }
            
            // Reserve space for the bottom navigation area
            Spacer(modifier = Modifier.height(180.dp))
        }

        // Skip Button at the top right
        if (pagerState.currentPage < pages.size - 1) {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .statusBarsPadding()
                    .padding(top = 8.dp, end = 16.dp),
                contentAlignment = Alignment.TopEnd
            ) {
                TextButton(onClick = onFinished) {
                    Text(
                        text = "Skip",
                        color = Color.White.copy(alpha = 0.9f),
                        fontWeight = FontWeight.Medium,
                        fontSize = 16.sp
                    )
                }
            }
        }

        // Bottom Navigation Area
        Column(
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .fillMaxWidth()
                .clip(RoundedCornerShape(topStart = 32.dp, topEnd = 32.dp))
                .background(Color(0xFF121212))
                .padding(32.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Page Indicators
            Row(
                modifier = Modifier.padding(bottom = 32.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                repeat(pages.size) { iteration ->
                    val width = animateDpAsState(targetValue = if (pagerState.currentPage == iteration) 32.dp else 8.dp, label = "")
                    Box(
                        modifier = Modifier
                            .height(8.dp)
                            .width(width.value)
                            .clip(CircleShape)
                            .background(
                                if (pagerState.currentPage == iteration) pages[pagerState.currentPage].backgroundColor else Color.Gray
                            )
                    )
                }
            }

            // Bottom Text Content is now inside the pager content for better layout
            // but we keep the button here for consistency
            
            Button(
                onClick = {
                    if (pagerState.currentPage < pages.size - 1) {
                        scope.launch { pagerState.animateScrollToPage(pagerState.currentPage + 1) }
                    } else {
                        onFinished()
                    }
                },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(60.dp), // Slightly taller for a more premium feel
                colors = ButtonDefaults.buttonColors(
                    containerColor = pages[pagerState.currentPage].backgroundColor
                ),
                shape = RoundedCornerShape(20.dp) // More rounded
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Center
                ) {
                    Text(
                        text = if (pagerState.currentPage == pages.size - 1) "Get Started" else "Continue",
                        fontSize = 18.sp,
                        fontWeight = FontWeight.Bold
                    )
                }
            }
        }
    }
}

@Composable
fun OnboardingPagerContent(page: OnboardingPage) {
    Column(
        modifier = Modifier.fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        // Image Area
        Box(
            modifier = Modifier
                .weight(1.2f)
                .fillMaxWidth()
                .padding(horizontal = 40.dp, vertical = 20.dp),
            contentAlignment = Alignment.Center
        ) {
            // Loading image from assets
            val context = LocalContext.current
            val bitmap = remember(page.imageAsset) {
                try {
                    context.assets.open(page.imageAsset).use { inputStream ->
                        BitmapFactory.decodeStream(inputStream)
                    }
                } catch (e: Exception) {
                    null
                }
            }
            
            if (bitmap != null) {
                Surface(
                    modifier = Modifier
                        .fillMaxHeight(0.9f)
                        .aspectRatio(1f),
                    shape = RoundedCornerShape(32.dp),
                    color = Color.White.copy(alpha = 0.05f)
                ) {
                    Image(
                        bitmap = bitmap.asImageBitmap(),
                        contentDescription = null,
                        modifier = Modifier.fillMaxSize().padding(24.dp),
                        contentScale = ContentScale.Fit
                    )
                }
            } else {
                Surface(
                    modifier = Modifier
                        .fillMaxHeight(0.9f)
                        .aspectRatio(1f),
                    shape = RoundedCornerShape(32.dp),
                    color = Color.White.copy(alpha = 0.1f),
                    border = ButtonDefaults.outlinedButtonBorder
                ) {
                    Column(
                        verticalArrangement = Arrangement.Center,
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        Icon(
                            imageVector = Icons.Default.School,
                            contentDescription = null,
                            tint = Color.White,
                            modifier = Modifier.size(64.dp)
                        )
                        Spacer(modifier = Modifier.height(16.dp))
                        Text("Image: ${page.imageAsset}", color = Color.White)
                        Text("Add to assets folder", color = Color.White.copy(alpha = 0.6f), fontSize = 12.sp)
                    }
                }
            }
        }

        // Text Area
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 32.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Text(
                text = page.title,
                color = Color.White,
                fontSize = 28.sp,
                fontWeight = FontWeight.Bold,
                textAlign = TextAlign.Center
            )
            Spacer(modifier = Modifier.height(16.dp))
            Text(
                text = page.description,
                color = Color.LightGray,
                fontSize = 16.sp,
                textAlign = TextAlign.Center,
                lineHeight = 24.sp
            )
        }
    }
}
